---
title: "Deep Learning Play"
author: "Max"
date: "Lets see"
output:
  html_document:
    code_folding: hide
    mathjax: default
    theme: united
    toc: yes
    toc_float: yes
    number_sections: TRUE
  pdf_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
cat("\014") # clear console
rm(list=ls()) # clear workspace
gc # garbage collector

require(pacman)
p_load(metafor, dplyr, tinytex, knitr, kableExtra, DescTools, reshape2, metaSEM, lavaan, semPlot, psych, ggplot2, keras, tensorflow)

set.seed(52) # set overall random seed for reproducibility
```

# Load Data
```{r LoadRawBase, echo=T, warning=F, message=F}

# Import Data
# dtRaw <- haven::read_spss(dir("M:/.00 Research/Snowballdata/raw data", pattern = "Agostini", full.names = TRUE, ignore.case = TRUE))
dtRaw <- haven::read_spss("M:/.00 Research/Snowball/PsyCorona-DataCleaning/data/collab data/c19 collab Data/RMD61 Thesis 2020/RMD61_Agostini_2021-09-29 19-25 UTC.sav")
```

# Prepare Data
## Cleaning
```{r clean, echo=T, warning=F, message=F}
# change all -99 into NA
  dtRaw[dtRaw == -99] <- NA

```

## Relevant vars
```{r}
# make a relevant dataframe
  tmp <- dtRaw %>%
  select(w21_affAnx, w21_affBor, w21_affEnerg, w21_affAng, w21_affLov,
         w22_VaccineYesNo)

# clean relevant dataframe
  tmp$w22_VaccineYesNo[tmp$w22_VaccineYesNo == 2] <- NA
  tmp$miss <- rowSums(is.na(tmp))
  
  dt <- tmp %>%
    filter(miss == 0) %>%
    select(-miss)
  
  rm(tmp)
  
# training data
  dtTrainX <- dt[1:(nrow(dt)*3/5),1:5]
  dtTestX <- dt[((nrow(dt)*3/5)+1):nrow(dt),1:5]
  train_data <- list(X = dt[1:(nrow(dt)*3/5),1:5],
                     Y = dt[1:(nrow(dt)*3/5),6] )
  train_data$y
  dtTrainY <- dt[1:(nrow(dt)*3/5),6]
  dtTestY <- dt[((nrow(dt)*3/5)+1):nrow(dt),6]
```

## Single-layer FNN
```{r}
# construct model
  fnn <- keras_model_sequential() 
fnn %>% 
  layer_dense(units = 5, activation = 'relu', input_shape = c(5)) %>% 
  layer_dense(units = 1, activation = 'sigmoid')

fnn %>% compile(
  loss = 'binary_crossentropy',
  optimizer = optimizer_adam(),
  metrics = c('accuracy')
)

# fit model
history = fnn %>% fit(
  as.matrix(train_data$X),
  as.matrix(train_data$Y), 
  epochs = 70,
  batch_size = 128)



fnn %>% evaluate(as.matrix(test_data$X), as.matrix(test_data$Y))
```

